name: my_daily_balance_flutter
description: A minimal Flutter project skeleton inside my_daily_balance for development.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  pdf: ^3.11.0
  printing: ^5.12.0
  excel: ^4.0.6
  google_fonts: ^6.3.2
  intl: ^0.20.2
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - .env
