name: kaccha_pakka_khata
description: A minimal Flutter project skeleton for Kaccha Pakka Khata.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  pdf: ^3.11.0
  printing: ^5.12.0
  google_fonts: ^7.0.2
  intl: ^0.20.2
  flutter_slidable: ^3.1.0
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  google_sign_in: ^7.2.0
  share_plus: ^7.2.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#FF1616"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
